CREATE DATABASE BD_HOTEL;

CREATE TABLE T_RECEPCIONISTA
(COD_RECEPCIONISTA INT IDENTITY(1,1) PRIMARY KEY ,
R_NOMBRE VARCHAR(40),
R_APELLIDO VARCHAR(40),
R_DNI CHAR(8)UNIQUE,
R_DIRECCION VARCHAR(50),
R_TELEFONO VARCHAR(9),
USUARIO VARCHAR(20)UNIQUE,
PASS VARCHAR(40)
);
INSERT INTO t_recepcionista( R_NOMBRE, R_APELLIDO, R_DNI, R_DIRECCION, R_TELEFONO, USUARIO, PASS) VALUES ('JUAN','JUAN','22336655','AV BRASIL','925479863','JUAN','123')
INSERT INTO t_recepcionista( R_NOMBRE, R_APELLIDO, R_DNI, R_DIRECCION, R_TELEFONO, USUARIO, PASS) VALUES ('LUIS','RIOS RIOS','22336688','AV ARGENTINA','925479864','LUIS','123')

CREATE TABLE T_NACIONALIDAD
(COD_NACIONALIDAD INT IDENTITY(1,1) PRIMARY KEY,
N_NACIONALIDAD VARCHAR(20)
);

INSERT INTO t_nacionalidad( N_NACIONALIDAD) VALUES ('PERU')
INSERT INTO t_nacionalidad( N_NACIONALIDAD) VALUES ('BOLIVIA')
INSERT INTO t_nacionalidad( N_NACIONALIDAD) VALUES ('COLOMBIA')

CREATE TABLE T_CLIENTE
(COD_CLIENTE INT IDENTITY(1,1) PRIMARY KEY,
C_DNI CHAR(8),
C_NOMBRE VARCHAR(30),
C_APELLIDO VARCHAR(30),
C_DIRECCION VARCHAR(30),
C_TELEFONO VARCHAR(30),
COD_NACIONALIDAD INT,
FOREIGN KEY(COD_NACIONALIDAD)REFERENCES T_NACIONALIDAD(COD_NACIONALIDAD)
);
INSERT INTO t_cliente(C_DNI, C_NOMBRE, C_APELLIDO, C_DIRECCION, C_TELEFONO, COD_NACIONALIDAD) VALUES ('22336655','JUAN','VACA LAGOS','AV BRASIL','963254789','1')

CREATE TABLE T_TIPO_HABITACION
(COD_TIPO_HABITACION INT IDENTITY(1,1) PRIMARY KEY,
TH_TIPO VARCHAR(20),
TH_NOMBRE VARCHAR(50),
TH_DESCRIPCION VARCHAR(50)
);
INSERT INTO t_tipo_habitacion(TH_TIPO, TH_NOMBRE, TH_DESCRIPCION) VALUES ('PERSONAL','NORMAL','UNA CAMA CON BAÑO PRIBADO')

CREATE TABLE T_HABITACION
(COD_HABITACION INT IDENTITY(1,1) PRIMARY KEY,
H_NUMERO INT,
H_COSTO DECIMAL,
H_ESTADO VARCHAR(20),
COD_TIPO_HABITACION INT,
FOREIGN KEY(COD_TIPO_HABITACION)REFERENCES T_TIPO_HABITACION
);
INSERT INTO t_habitacion( H_NUMERO, H_COSTO, H_ESTADO, COD_TIPO_HABITACION) VALUES ('1','25.00','ALQUILADA','1')

CREATE TABLE T_ALQUILER
(COD_ALQUILER INT IDENTITY(1,1) PRIMARY KEY,
A_FECHA_INICIO DATETIME,
A_FECHA_FIN DATETIME,
A_DIAS INT,
COD_HABITACION INT,
COD_CLIENTE INT,
COD_RECEPCIONISTA INT,
FOREIGN KEY(COD_HABITACION)REFERENCES T_HABITACION(COD_HABITACION),
FOREIGN KEY(COD_CLIENTE)REFERENCES T_CLIENTE(COD_CLIENTE),
FOREIGN KEY(COD_RECEPCIONISTA)REFERENCES T_RECEPCIONISTA(COD_RECEPCIONISTA)
);
INSERT INTO t_alquiler(A_FECHA_INICIO, A_FECHA_FIN, A_DIAS, COD_HABITACION, COD_CLIENTE, COD_RECEPCIONISTA) VALUES ('2021-11-29','2021-11-30','2','1','1','1')